simplemooc/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .views import register, dashboard, edit

app_name = 'accounts'

urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('entrar/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('cadastra-se/', register, name='register'),
    path('editar/', edit, name='edit'),
    path('sair/', auth_views.LogoutView.as_view(next_page='core:home'), name='logout')
]

simplemooc/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('contato/', views.contact, name='contact')
]

simplemooc/courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:slug>/', views.details, name='details')
]

simplemooc/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import serve

urlpatterns = [
    path('', include('simplemooc.core.urls', namespace='core')),
    path('cursos/', include('simplemooc.courses.urls', namespace='courses')),
    path('conta/', include('simplemooc.accounts.urls', namespace='accounts')),
    path('admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

simplemooc/accounts/models.py
from django.db import models

# Create your models here.

simplemooc/courses/models.py
from django.db import models

class CourseManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name__icontains=query) |
            models.Q(description__icontains=query)
        )


class Course(models.Model):

    name = models.CharField('Nome', max_length=100)
    slug = models.SlugField('Atalho')
    description = models.TextField('Descrição', blank=True)
    about = models.TextField("Sobre o curso", blank=True)
    start_date = models.DateField('Data de Início', null=True, blank=True)
    image = models.ImageField(
        upload_to='courses/images', verbose_name='Imagem', null=True, blank=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)

    objects = CourseManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse("courses:details", kwargs={"slug": self.slug})
    

    class Meta:
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'
        ordering = ['name']

simplemooc/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField(label='E-mail')

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("Já existe usuário com este e-mail.")
        return email

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class EditAccountForm(forms.ModelForm):

    def clean_email(self):
        email = self.cleaned_data['email']
        queryset = User.objects.filter(
            email=email).exclude(pk=self.instance.pk)
        if queryset.exists():
            raise forms.ValidationError("Já existe usuário com este e-mail.")
        return email

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

simplemooc/courses/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

from simplemooc.core.mail import send_mail_template


class ContactCourse(forms.Form):
    name = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='E-mail')
    message = forms.CharField(label='Mensagem/Dúvida', widget=forms.Textarea)

    def send_mail(self, course):
        subject = '[%s] Contato' % course
        message = 'Nome: %(name)s;E-mail: %(email)s;%(message)s'
        context = {
            'name': self.cleaned_data['name'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }
        message = message % context
        template_name = 'contact_email.html'
        send_mail_template(subject, template_name, context,
                           [settings.CONTACT_EMAIL])

simplemooc/accounts/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required

from django.contrib.auth.forms import UserCreationForm
from .forms import RegisterForm, EditAccountForm


@login_required
def dashboard(request):
    template_name = 'dashboard.html'
    return render(request, template_name)


def register(request):
    template_name = 'register.html'
    form = None
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user = authenticate(username=user.username,
                                password=form.cleaned_data['password1'])
            login(request, user)
            return redirect('core:home')

    else:
        form = RegisterForm()
    context = {
        'form': form
    }
    return render(request, template_name, context)


@login_required
def edit(request):
    template_name = 'edit.html'
    form = EditAccountForm()
    context = {}
    if request.method == 'POST':
        form = EditAccountForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            form = EditAccountForm(instance=request.user)
            context['success'] = True
    else:
        form = EditAccountForm(instance=request.user)
    context['form'] = form
    return render(request, template_name, context)

simplemooc/core/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.


def home(request):
    return render(request, 'home.html')

def contact(request):
    return render(request, 'contact.html')

simplemooc/courses/views.py
from django.shortcuts import render, get_object_or_404
from .models import Course
from .forms import ContactCourse


def index(request):
    courses = Course.objects.all()
    context = {
        'courses': courses
    }
    return render(request, "index.html", context)


def details(request, slug):
    course = get_object_or_404(Course, slug=slug)
    form = None
    context = {}
    if request.method == 'POST':
        form = ContactCourse(request.POST)
        if form.is_valid():
            context['is_valid'] = True
            form.send_mail(course.name)
            form = ContactCourse()
    else:
        form = ContactCourse()
    context['course'] = course
    context['form'] = form
    return render(request, 'details.html', context)

simplemooc/accounts/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon">
        <div class="pure-u-1">
            <ul class="breadcrumb">
                {% block breadcrumb %}
                <li><a href="{% url 'accounts:dashboard' %}">Meu Painel</a></li>
                {% endblock breadcrumb %}
            </ul>
        </div>
        <div class="pure-u-1-3">
            <div class="pure-menu pure-menu-open">
                <a class="pure-menu-heading">Meus Cursos</a>
                <ul>
                    <li><a href="#">Curso 1</a></li>
                    <li><a href="#">Curso 2</a></li>
                    <li class="pure-menu-heading">Minha Conta</li>
                    <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
                    <li><a href="#">Editar Senha</a></li>
                </ul>
            </div>
        </div>
        <div class="pure-u-2-3">
            <div class="inner">
                {% block dashboard_content %}
                <p><strong>Usuário</strong>: {{ user.username }}</p>
                <p><strong>E-mail</strong>: {{ user.email }}</p>
                {% endblock dashboard_content %}
            </div>
        </div>
    </div>
{% endblock content %}

simplemooc/accounts/templates/edit.html
{% extends 'dashboard.html' %}

{% block breadcrumb %}
    {{ block.super }}
    <li>/</li>
    <li><a href="{% url 'accounts:edit' %}">Editar Conta</a></li>
{% endblock breadcrumb %}

{% block dashboard_content %}
<form method='POST' class="pure-form pure-form-stacked">
    {% csrf_token %}
    {% if success %}
    <p>Os dados foram alterdos com sucesso</p>
    {% endif %}
    <fieldset>
        {{ field.non_field_errors }}
        {% for field in form %}
        <div class="pure-control-group">
            {{ field.label_tag}}
            {{ field }}
           {{ field.errors }}
        </div>
        {% endfor %}

        <div class="pure-controls">
            <button type="submit" class="pure-button pure-button-primary">Enviar</button>
        </div>
    </fieldset>
</form>
{% endblock dashboard_content %}

simplemooc/accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados de cadastro</h2>
        <form method='post' class="pure-form pure-form-stacked">
            {% csrf_token %}
            <fieldset>
                {{ form.non_field_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors}}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Entrar</button>
                </div>
            </fieldset>
            <p>
                Não é cadastrado? <a href="{% url 'accounts:register' %}" title="">Cadastre-se</a> <br />
                Esqueceu a senha? <a href="" title="">Nova senha</a> <br />
            </p>
        </form>
    </div>
</div>
{% endblock content %}

simplemooc/accounts/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <h2>Informe seus dados</h2>
        <form method='post' class="pure-form pure-form-stacked">
            {% csrf_token %}
            <fieldset>
                {{ form.non_form_errors }}

                {% for field in form %}
                <div class="pure-control-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {{ field.errors}}
                </div>
                {% endfor %}
                <div class="pure-controls">
                    <button type="submit" class="pure-button pure-button-primary">Cadastrar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock content %}

simplemooc/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="Simple MOOC - Uma simples plataforma de ensino a distância"
    />
    <title>Simple MOOC</title>
    <link
      rel="stylesheet"
      href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css"
    />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <div class="header">
        <div
            class="pure-menu pure-menu-open pure-menu-fixed pure-menu-horizontal"
        >
            <a class="pure-menu-heading" href="{% url 'core:home' %}">SIMPLE MOOC</a>
            <ul>
            <li class="pure-menu-selected"><a href="{% url 'core:home' %}">Início</a></li>
            <li><a href="{% url 'courses:index' %}">Cursos</a></li>
            <li><a href="{% url 'core:contact' %}">Contato</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'accounts:dashboard'%}">Painel</a></li>
            <li><a href="{% url 'accounts:logout'%}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'accounts:login'%}">Entrar</a></li>
            {% endif %}
            </ul>
        </div>
    </div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
    <div class="footer">
        Simple MOOC - Uma simples plataforma de ensino a distância
    </div>
    <script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
  </body>
</html>

simplemooc/core/templates/contact.html
{% extends "base.html" %}

{% block content %}
  <div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
      <h1>Fale conosco</h1>
      <p>
        Você pode entrar em contato conosco tanto por e-mail como pelas
        redes sociais, abaixo seguem os links para contato:
      </p>
      <h4>Links</h4>
      <ul>
        <li>
          E-mail:
          <a href="mailto:contato@simplemooc.org">contato@simplemooc.org</a>
        </li>
        <li>
          Twitter: <a href="https://twitter.com/simplemooc">@simplemooc</a>
        </li>
      </ul>
    </div>
  </div>
{% endblock content %}

simplemooc/core/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="splash">
        <div class="pure-g-r">
          <div class="pure-u-1">
            <div class="l-box splash-text">
              <h1 class="splash-head">
                Uma Simples Plataforma de Ensino a Distância
              </h1>
              <h2 class="splash-subhead">
                O Simple MOOC visa simplificar o ensino a distância, provendo
                ferramentas objetivas e de fácil uso para cursos a distância.
              </h2>
              <p>
                <a href="#" class="pure-button primary-button">Saiba mais</a>
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="pure-g-r content-ribbon">
          <div class="pure-u-2-3">
            <div class="l-box">
              <h4 class="content-subhead">Vídeo-aulas e materiais digitais</h4>
              <h3>Publique suas aulas</h3>
              <p>
                O Simple MOOC tem um sistema simples e prático para que o
                professor disponibilize vídeo-aulas e materiais digitais como:
                pdf's, slides, imagens ...
              </p>
            </div>
          </div>
          <div class="pure-u-1-3">
            <div class="l-box">
              <img
                src="http://placehold.it/400x250"
                alt="Vídeo aulas e materiais digitais."
              />
            </div>
          </div>
        </div>
        <div class="pure-g-r content-ribbon">
          <div class="pure-u-1-3">
            <div class="l-box">
              <img src="http://placehold.it/400x250" alt="Fórum de Dúvidas" />
            </div>
          </div>
          <div class="pure-u-2-3">
            <div class="l-box">
              <h4 class="content-subhead">Fórum de Dúvidas</h4>
              <h3>Interaja com seus Alunos</h3>
              <p>
                No Simple MOOC você pode ter seu próprio sistema de fórum para
                que seus alunos possam interagir com você e com os outros alunos
              </p>
            </div>
          </div>
        </div>
        <div class="pure-g-r content-ribbon">
          <div class="pure-u-2-3">
            <div class="l-box">
              <h4 class="content-subhead">Exercícios</h4>
              <h3>Crie exercícios para avaliar seus alunos</h3>
              <p>
                Você pode criar exercícios para que os alunos possam ser
                avaliados e todo o controle de notas e resolução dos exercícios
                é controlado pela plataforma, facilitando sua vida
              </p>
            </div>
          </div>
          <div class="pure-u-1-3">
            <div class="l-box">
              <img src="http://placehold.it/400x250" alt="Exercícios" />
            </div>
          </div>
        </div>
        <div class="pure-g-r content-ribbon">
          <div class="pure-u-1-3">
            <div class="l-box">
              <img src="http://placehold.it/400x250" alt="Mural de Avisos" />
            </div>
          </div>
          <div class="pure-u-2-3">
            <div class="l-box">
              <h4 class="content-subhead">Mural de Avisos</h4>
              <h3>Envie anúncios diretamente para os alunos</h3>
              <p>
                Organize os avisos do seu curso de forma fácil e simples.
              </p>
            </div>
          </div>
        </div>
    </div>
{% endblock content %}
      

simplemooc/courses/templates/contact_email.html
<p><strong>Nome</strong>: {{ name }}</p>
<p><strong>E-mail</strong>: {{ email }}</p>
{{ message|linebreaks }}

simplemooc/courses/templates/details.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="splash">
    <div class="pure-g-r">
        <div class="pure-u-1">
            <div class="l-box splash-text">
                <h1 class="splash-head">
                    {{ course }}
                </h1>
                <h2 class="splash-subhead">
                    {{ course.description }}
                </h2>
                <p>
                    <a href="#" class="pure-button primary-button">Inscreva-se</a>
                </p>
            </div>
        </div>
    </div>
</div>
<div class="pure-g-r content-ribbon">
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead">Sobre o Curso</h4>
            {{ course.about|linebreaks }}
        </div>
    </div>
    <div class="pure-u-1-3">
        <div class="l-box">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="" />
            {% endif %}
            <h4>Dúvidas?</h4>
            <p>
                <a href="#contato" title="" class="pure-button">Fale Conosco</a>
            </p>
        </div>
    </div>
</div>
<div class='pure-g-r content-ribbon' id='contato'>
    <div class='pure-u-1'>
        <h3>Tire sua dúvida sobr eo Curso</h3>
        {% if is_valid %}
        <p>Formulário enviado com sucesso</p>
        {% endif %}
        <form action='#contato' method='post' class='pure-form pure-form-aligned'>
            {% csrf_token %}
            <fieldset>
                {% for field in form %}
                <div class='pure-control-group'>
                    {{ field.label_tag }}
                    {{ field }}
                    {% if fields.errors %}
                    <ul class='errorList'>
                        {% for error in fields.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
                {% endfor %}
                <div class='pure-controls'>
                    <button type='submit' class='pure-button pure-button-primary'>Enviar</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
{% endblock %}

simplemooc/courses/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <h4 class="content-subhead">Listagem de Cursos do SimpleMOOC</h4>
            <p>Abaixo a lista de cursos disponíveis na plataforma</p>
        </div>
    </div>
</div>
{% for course in courses %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1-3">
        <div class="l-box">
            <a href="{{ course.get_absolute_url }}">
            {% if course.image %}
            <img src="{{ course.image.url }}" alt="{{ course.name }}" />
            {% else %}
            <img src="{% static 'img/course-image.png' %}" alt="{{ course.name }}" />
            {% endif %}
            </a>
        </div>
    </div>
    <div class="pure-u-2-3">
        <div class="l-box">
            <h4 class="content-subhead"><a href="{{ course.get_absolute_url }}" title="">{{ course.name }}</a></h4>
            {{ course.description|linebreaks }}
        </div>
    </div>
</div>
{% empty %}
<div class="pure-g-r content-ribbon">
    <div class="pure-u-1">
        <div class="l-box">
            <p>Nenhum curso está disponível na plataforma</p>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}